; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=riscv32 -mattr=+experimental-xqccmp,+e -target-abi ilp32e -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV32

define ptr @func(ptr %s, i32 %_c, ptr %incdec.ptr, i1 %0, i8 %conv14) #0 {
; RV32-LABEL: func:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    li a5, 1
; RV32-NEXT:    andi t0, a3, 1
; RV32-NEXT:  .LBB0_1: # %while.body
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    mv a3, a5
; RV32-NEXT:    li a5, 0
; RV32-NEXT:    bnez t0, .LBB0_1
; RV32-NEXT:  # %bb.2: # %while.end
; RV32-NEXT:    slli a5, a1, 16
; RV32-NEXT:    andi a3, a3, 1
; RV32-NEXT:    add a1, a1, a5
; RV32-NEXT:    add a2, a2, a3
; RV32-NEXT:    slli a3, a1, 8
; RV32-NEXT:    add a1, a1, a3
; RV32-NEXT:    sw a1, 0(zero)
; RV32-NEXT:    sb a4, 0(a2)
; RV32-NEXT:    ret
entry:
  br label %while.body

while.body:                                       ; preds = %while.body, %entry
  %n.addr.042 = phi i32 [ 1, %entry ], [ 0, %while.body ]
  br i1 %0, label %while.body, label %while.end

while.end:                                        ; preds = %while.body
  %or5 = mul i32 %_c, 16843009
  store i32 %or5, ptr null, align 4
  %1 = and i32 %n.addr.042, 1
  %scevgep = getelementptr i8, ptr %incdec.ptr, i32 %1
  store i8 %conv14, ptr %scevgep, align 1
  ret ptr %s
}
